# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.10.21

install:
  - pip install -U tox-travis
  - pip install -r requirements_dev.txt

# Command to run tests
# script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: invinciblycool/py5paisa
    python: 3.10.21
